### ISSUE TITLE
unmatched '('

### ISSUE THREAD

**Issue by alexey-tyulkin** [docopt/docopt.net#32]
```c#
using DocoptNet;
namespace ConsoleApplication1 {
    internal class Program {
        private static void Main(string[] args) {
            const string USAGE =
@"Usage: Conversion (load | brokers | loadnonxl | <pn>... [--clean]) [--whatif]

-h --help    show this
--verbose    print more text
";

            var docopt = new Docopt();
            var arguments = docopt.Apply(USAGE, args, exit: true);
        }
    }
}
```

prints 
**unmatched '('**
but http://try.docopt.org/?doc=Usage%3A+Conversion+%28load+%7C+brokers+%7C+loadnonxl+%7C+%3Cpn%3E...+%5B--clean%5D%29+%5B--whatif%5D%0D%0A%0D%0A-h+--help++++show+this%0D%0A--verbose++++print+more+text&argv=dfg67+dfg4+dg2+--clean

parse it

**Comment by voieducode** [comment]
I will have a look

On 23 Apr 2017 13:06, "alexey-tyulkin" <notifications@github.com> wrote:

using DocoptNet;namespace ConsoleApplication1 {
    internal class Program {
        private static void Main(string[] args) {
            const string USAGE =
@"Usage: Conversion (load | brokers | loadnonxl | <pn>... [--clean])
[--whatif]-h --help    show this--verbose    print more text";

            var docopt = new Docopt();
            var arguments = docopt.Apply(USAGE, args, exit: true);
        }
    }
}

prints
*unmatched '('*
but http://try.docopt.org/?doc=Usage%3A+Conversion+%28load+%
7C+brokers+%7C+loadnonxl+%7C+%3Cpn%3E...+%5B--clean%5D%29+%
5B--whatif%5D%0D%0A%0D%0A-h+--help++++show+this%0D%0A--
verbose++++print+more+text&argv=dfg67+dfg4+dg2+--clean

parse it

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docopt/docopt.net/issues/32>, or mute the thread

**Comment by alexey-tyulkin** [comment]
There is additional example 

> unmatched '('

```c#
   private const string USAGE =
@"Usage: 
    copy_acl <masterid> ((--source|-s) <source>)... ((--target|-t) <target>)...  [--whatif] [--debugger] 

-h --help    show this
--verbose    print more text
";
```

**Comment by oliverholliday** [comment]
I have this also with any Usage block which includes multiple `...`s

```
Usage
  configure [--key=NAME]... [--adminKey=NAME]...
```

```
> configure --key=one --key=two
unmatched '('
```
