### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by alashworth** [docopt/docopt.net#4]
Hi,

I'm new to .NET development, so when I saw that DocOpt had been ported from Python, I was very excited.  However, I am unable to get even the Naval Fate example to run without an exception. 

I am using Visual Studio Express 2012 for Windows Desktop and the current docoptnet from NuGet. The exception reads as follows at the bottom of the comment.

So it looks like DocOpt can't parse the usage string. Is there some setting I am missing? Maybe something to do with how the IDE handles tabs and spaces?

```
  An unhandled exception of type 'DocoptNet.DocoptInputErrorException' occurred in DocoptNet.dll

  Additional information: Usage:

  naval_fate.exe ship new <name>...

  naval_fate.exe ship <name> move <x> <y> [--speed=<kn>]

  naval_fate.exe ship shoot <x> <y>

  naval_fate.exe mine (set|remove) <x> <y> [--moored | --drifting]

  naval_fate.exe (-h | --help)

  naval_fate.exe --version
```

**Comment by raknasa** [comment]
Even with the try I still dont get information that helps me. I can of course supress the error, ,but... I would like to understand why it there in the first place

**Comment by iwillspeak** [comment]
The error is there because Docopt can’t parse the command line successfully. In the case you showed passing —help means that Docopt should show the help text and exit. I believe exceptions are used here to make the handling of the exceptional case that the command line doesn’t parse successfully a bit cleaner to deal with.  With an exception most of the code in `Main` doesn’t need to worry about checking the arguments. They were either valid according to the unseage, or the process will have exited with an error. 

If you don’t want exceptions here you can set exit to true and the process will exit rather than throwing an exception. Either that or catch the exception and handle it however you want.

**Comment by povociancioni** [comment]
![Capture d’écran (35)](https://user-images.githubusercontent.com/65611854/103621243-30788d80-4f35-11eb-9f2d-15f812b224d5.png)
Happy New Year!
As a programming user  I d be happy if I could be oriented towards the documentation I need to better understand how to make an attractive user menu. For instance, one first problem that I am confronted to is answering : why isn't "Naval Fate 2.0" appearing into the output? Did I miss to correctly input an argument?
Would you show me the very next step beyond this first code?
`internal class Program{
private const string usage = @"Naval Fate.
Usage : 
Options : 
";
private static void Main(string[] args){
try{
var arguments = new Docopt().Apply(usage, args, version : "Naval Fate 2 .0");
foreach (var argument in arguments){
Console.WriteLine("{0} = {1}", argument.Key, argument.Value);
}
}
catch (Exception e){
Console.WriteLine(e.Message);
}
}
}
`

**Comment by voieducode** [comment]
Docopt does not generate a menu, it will just use the docstring you
provided to parse the command line. Try "Usage:" instead of "Usage :"
(extra space), and make sure you provide an actual usage text. Try to use
the USAGE string given in the example below (as per docopt.net/README.rst
at master · docopt/docopt.net · GitHub
<https://github.com/docopt/docopt.net/blob/master/README.rst>):

const string USAGE =@"Usage: my_program [-hso FILE] [--quiet |
--verbose] [INPUT ...]-h --help    show this-s --sorted  sorted
output-o FILE      specify output file [default: ./test.txt]--quiet
  print less text--verbose    print more text";

**Comment by povociancioni** [comment]
I've been renewing work on it and I happened to find out this screen as a result. Is it the right code to run?
![Capture d’écran (36)](https://user-images.githubusercontent.com/65611854/104599927-a50ba480-5678-11eb-9ce1-bbca9a80c17f.png)

**Comment by voieducode** [comment]
Yes that is correct. However it looks like there is an unmatched [ in the
code you are running. Did you manage to fix that?

**Comment by povociancioni** [comment]
I'm afraid not.

**Comment by voieducode** [comment]
Can you share the code you are running?

**Comment by povociancioni** [comment]
https://www.dropbox.com/scl/fi/x3kn2fknooe7ez65ddbq5/shared.paper?dl=0&rlkey=y86004ikqk9l365ehkux1ab85


Thank you

**Comment by povociancioni** [comment]
![Capture d’écran (37)](https://user-images.githubusercontent.com/65611854/104832736-859c9380-5893-11eb-986b-a28bb82b3391.png)

**Comment by voieducode** [comment]
Can you use https://gist.github.com/ - I was not able to copy from your link?

**Comment by povociancioni** [comment]
[](url)https://gist.github.com/povociancioni/297e496263f7a5ef393f3849410dc9e9

**Comment by povociancioni** [comment]
You seem to have forgotten me? Haven't you?

**Comment by voieducode** [comment]
Sorry did not manage to reproduce your problem yet - try to build directly
the example in the samples folder of the repo, that worked for me
